import type { Clip, Project, Track, TrackKind } from '../types/editor';
const id = (prefix: string) => `${prefix}_${Math.random().toString(36).slice(2)}_${Date.now().toString(36)}`;
const clone = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
function findClip(project: Project, clipId: string): { track: Track; clip: Clip; index: number } { for (const track of project.tracks) { const index = track.clips.findIndex((clip) => clip.id === clipId); if (index >= 0) return { track, clip: track.clips[index], index }; } throw new Error(`Clip not found: ${clipId}`); }
export function createProject(userId: string, name = 'Nebula Cut Project'): Project { return { id: id('project'), userId, name, fps: 30, width: 1920, height: 1080, tracks: [{ id: id('track'), kind: 'video', name: 'Video 1', clips: [] }, { id: id('track'), kind: 'audio', name: 'Audio 1', clips: [] }, { id: id('track'), kind: 'text', name: 'Text 1', clips: [] }, { id: id('track'), kind: 'overlay', name: 'Overlay 1', clips: [] }, { id: id('track'), kind: 'effect', name: 'Effects', clips: [] }], updatedAt: new Date().toISOString() }; }
export function addTrack(project: Project, kind: TrackKind, name: string): Project { const next = clone(project); next.tracks.push({ id: id('track'), kind, name, clips: [] }); next.updatedAt = new Date().toISOString(); return next; }
export function addClip(project: Project, trackId: string, clip: Omit<Clip, 'id' | 'trackId' | 'keyframes'> & { id?: string }): Project { const next = clone(project); const track = next.tracks.find((item) => item.id === trackId); if (!track) throw new Error(`Track not found: ${trackId}`); track.clips.push({ ...clip, id: clip.id ?? id('clip'), trackId, keyframes: {} }); track.clips.sort((a, b) => a.startMs - b.startMs); next.updatedAt = new Date().toISOString(); return next; }
export function trimClip(project: Project, clipId: string, sourceInMs: number, durationMs: number): Project { if (durationMs <= 0) throw new Error('Duration must be positive'); const next = clone(project); const { clip } = findClip(next, clipId); clip.sourceInMs = Math.max(0, sourceInMs); clip.durationMs = durationMs; next.updatedAt = new Date().toISOString(); return next; }
export function splitClip(project: Project, clipId: string, atMs: number): Project { const next = clone(project); const { track, clip, index } = findClip(next, clipId); const relative = atMs - clip.startMs; if (relative <= 0 || relative >= clip.durationMs) throw new Error('Split point must be inside clip'); const right: Clip = { ...clone(clip), id: id('clip'), startMs: atMs, sourceInMs: clip.sourceInMs + relative / clip.speed, durationMs: clip.durationMs - relative }; clip.durationMs = relative; track.clips.splice(index + 1, 0, right); next.updatedAt = new Date().toISOString(); return next; }
export function moveClip(project: Project, clipId: string, targetTrackId: string, startMs: number): Project { const next = clone(project); const { track, clip, index } = findClip(next, clipId); track.clips.splice(index, 1); const target = next.tracks.find((item) => item.id === targetTrackId); if (!target) throw new Error(`Track not found: ${targetTrackId}`); target.clips.push({ ...clip, trackId: targetTrackId, startMs: Math.max(0, startMs) }); target.clips.sort((a, b) => a.startMs - b.startMs); next.updatedAt = new Date().toISOString(); return next; }
export function duplicateClip(project: Project, clipId: string): Project { const next = clone(project); const { track, clip } = findClip(next, clipId); track.clips.push({ ...clone(clip), id: id('clip'), startMs: clip.startMs + clip.durationMs }); track.clips.sort((a, b) => a.startMs - b.startMs); next.updatedAt = new Date().toISOString(); return next; }
export function deleteClip(project: Project, clipId: string): Project { const next = clone(project); const { track, index } = findClip(next, clipId); track.clips.splice(index, 1); next.updatedAt = new Date().toISOString(); return next; }
export function setClipProperty<K extends keyof Clip>(project: Project, clipId: string, key: K, value: Clip[K]): Project { const next = clone(project); const { clip } = findClip(next, clipId); clip[key] = value; next.updatedAt = new Date().toISOString(); return next; }
